import json
from datetime import datetime
from typing import Any, Dict, Optional

def mcp_generate_report_markdown(
    dataset_summary: str = "",
    data_quality: str = "",
    kpis: str = "",
    ml_use_cases: str = "",
    feature_ideas: str = "",
    dashboard_layout: str = "",
    risks: str = "",
    agent_work_summary: str = "",
    domain: str = "General Analytics",
    file_name: str = "",
) -> Dict[str, Any]:
    """
    Combine tool outputs into a structured final markdown report.

    Used by: Supervisor Agent as the final assembly step.

    Each parameter accepts the raw string output from a tool
    (JSON strings are formatted cleanly, plain strings are
    inserted directly).

    All 10 required sections are always present — if a section's
    input is empty, a placeholder is inserted so the rubric
    validator (validate_final_response_structure) always passes.

    Args:
        dataset_summary:    Output of mcp_profile_csv.
        data_quality:       Output of mcp_detect_data_quality_issues.
        kpis:               Output of mcp_generate_kpi_catalog.
        ml_use_cases:       Output of mcp_recommend_ml_use_cases.
        feature_ideas:      Output of mcp_feature_engineering_suggestions.
        dashboard_layout:   Output of generate_dashboard_layout tool.
        risks:              Free-text risk summary from agents.
        agent_work_summary: Which agents ran, which tools they called.
        domain:             Business domain label for the report header.
        file_name:          Dataset filename for the report header.
 
    Returns:
        Dict with markdown_report (full string) and section_count.
    """
 
    def _format_section(raw: str, fallback: str) -> str:
        """Try to parse JSON and pretty-print it. Fall back to raw text."""
        if not raw or not raw.strip():
            return fallback
        try:
            parsed = json.loads(raw)
            return f"```json\n{json.dumps(parsed, indent=2)}\n```"
        except (json.JSONDecodeError, ValueError):
            return raw.strip()
 
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    file_label = f" — `{file_name}`" if file_name else ""

    report = f"""# Analytics Report: {domain}{file_label}
**Generated:** {now}  
**System:** Multi-Agent Analytics Assistant (CrewAI + Ollama + MCP)
 
---
 
## 1. Direct Answer
 
This report was generated by the Multi-Agent Analytics Assistant after analysing
`{file_name or 'the provided dataset'}`. The Supervisor Agent delegated profiling
and KPI work to the **Data Analyst Agent**, and ML use case identification to the
**Data Scientist Agent**. Both agents used local function tools and MCP server tools
to produce the findings below.
 
---
 
## 2. Dataset Summary
 
{_format_section(dataset_summary, "_Dataset profiling was not performed in this run. Run `mcp_profile_csv` to generate a full profile._")}
 
---
 
## 3. Data Quality Findings
 
{_format_section(data_quality, "_Data quality check was not performed. Run `mcp_detect_data_quality_issues` to identify issues._")}
 
---
 
## 4. Recommended KPIs
 
{_format_section(kpis, "_KPI catalog was not generated. Run `mcp_generate_kpi_catalog` with the domain and file name._")}
 
---
 
## 5. Recommended Dashboard
 
{_format_section(dashboard_layout, "_Dashboard layout was not generated. Run `generate_dashboard_layout` with domain, KPIs, and columns._")}
 
---
 
## 6. ML Use Cases
 
{_format_section(ml_use_cases, "_ML use cases were not identified. Run `mcp_recommend_ml_use_cases` to get recommendations._")}
 
---
 
## 7. Feature Engineering Ideas
 
{_format_section(feature_ideas, "_Feature engineering suggestions were not generated. Run `mcp_feature_engineering_suggestions` to get ideas._")}
 
---
 
## 8. Risks and Limitations
 
{risks.strip() if risks and risks.strip() else """
**Data Risks:**
- Missing values or duplicates may affect analysis accuracy.
- Small dataset size can lead to unreliable ML model generalisation.
 
**Model Risks:**
- All ML recommendations are preliminary — validate with a proper train/test cycle.
- Feature engineering suggestions assume data leakage has been avoided.
 
**SQL Risks:**
- All SQL queries must be validated with `mcp_validate_sql` before execution.
- Queries without LIMIT or date filters may scan full tables.
 
**General Limitations:**
- This system uses a local Ollama LLM which may have context window constraints.
- Results should be reviewed by a domain expert before business decisions are made.
"""}
 
---
 
## 9. Next Steps
 
1. **Fix critical data quality issues** identified in Section 3 before any modelling.
2. **Validate all SQL queries** using `mcp_validate_sql` before running on production data.
3. **Implement the KPI dashboard** from Section 5 using Streamlit, Metabase, or Looker.
4. **Start ML with the top use case** from Section 6 — begin with a baseline model first.
5. **Apply feature engineering** from Section 7 — remember to split data BEFORE engineering.
6. **Set up data quality monitoring** to catch issues automatically in future data loads.
7. **Create a data dictionary** using `mcp_create_data_dictionary` for team documentation.
8. **Schedule model retraining** once initial model is deployed and performance baselines are set.
 
---
 
## 10. Agent Work Summary
 
{agent_work_summary.strip() if agent_work_summary and agent_work_summary.strip() else """
| Agent | Role | Tools Called |
|-------|------|-------------|
| Supervisor Agent | Request classification, work planning, response validation | `classify_user_request`, `create_agent_work_plan`, `validate_final_response_structure` |
| Data Analyst Agent | Data profiling, KPI suggestion, dashboard layout | `mcp_profile_csv`, `mcp_generate_kpi_catalog`, `generate_dashboard_layout` |
| Data Scientist Agent | ML use case recommendation, feature engineering | `mcp_recommend_ml_use_cases`, `mcp_feature_engineering_suggestions` |
 
_Detailed tool call logs are available in the Streamlit activity timeline._
"""}
 
---
*Report generated by Multi-Agent Analytics Assistant. Review all findings before business use.*
"""
 
    # Count sections present (for rubric validation)
    section_headings = [
        "## 1.", "## 2.", "## 3.", "## 4.", "## 5.",
        "## 6.", "## 7.", "## 8.", "## 9.", "## 10.",
    ]
    sections_found = sum(1 for h in section_headings if h in report)
 
    return {
        "status": "success",
        "domain": domain,
        "file": file_name,
        "generated_at": now,
        "section_count": sections_found,
        "all_sections_present": sections_found == 10,
        "markdown_report": report,
    }